export type ServiceType = 'review_booster' | 'ugc_creator' | 'local_influencer' | 'social_boost';

export type Network = 'instagram' | 'tiktok' | 'facebook' | 'youtube' | 'multi';

export type Gender = 'female' | 'male' | 'team' | 'unspecified';

export interface MarketplaceService {
  id: string;
  name: string;
  handle: string;           // e.g. @joburgfoodie
  network: Network;
  location: string;         // free text: "Parkhurst, Johannesburg"
  city: string;             // normalized: "Johannesburg"
  suburb: string;           // normalized: "Parkhurst"
  interests: string[];      // e.g. ['Food & Dining', 'Local Gems']
  followers: number;        // numeric
  gender: Gender;
  serviceTypes: ServiceType[];
  startingFrom: number;     // e.g. 1200 (ZAR)
  shortPitch: string;       // 1-liner value prop
  metricsBlurb?: string;    // e.g. "Avg 6.2% engagement"
  avatarUrl?: string;       // placeholder/avatar
  rating?: number;          // 4.8 etc (dummy)
  completedJobs?: number;   // dummy social proof
}

// Dummy data - ~18 entries
export const DUMMY_SERVICES: MarketplaceService[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    handle: '@joburgfoodie',
    network: 'instagram',
    location: 'Parkhurst, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Parkhurst',
    interests: ['Food & Dining', 'Local Gems'],
    followers: 12500,
    gender: 'female',
    serviceTypes: ['review_booster', 'ugc_creator', 'local_influencer'],
    startingFrom: 1200,
    shortPitch: 'Food blogger specializing in local restaurants and hidden gems in Joburg.',
    metricsBlurb: 'Avg 6.2% engagement',
    rating: 4.8,
    completedJobs: 47,
    avatarUrl: 'https://ui-avatars.com/api/?name=Sarah+Mitchell&size=128&background=ff6b9d&color=fff&bold=true',
  },
  {
    id: '2',
    name: 'Mike Chen',
    handle: '@capetownfitness',
    network: 'multi',
    location: 'Sea Point, Cape Town',
    city: 'Cape Town',
    suburb: 'Sea Point',
    interests: ['Fitness', 'Wellness'],
    followers: 45000,
    gender: 'male',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 2500,
    shortPitch: 'Fitness influencer creating high-energy workout content and product reviews.',
    metricsBlurb: 'Avg 8.1% engagement',
    rating: 4.9,
    completedJobs: 89,
    avatarUrl: 'https://ui-avatars.com/api/?name=Mike+Chen&size=128&background=4f46e5&color=fff&bold=true',
  },
  {
    id: '3',
    name: 'Beauty Collective SA',
    handle: '@beautycollectivesa',
    network: 'instagram',
    location: 'Sandton, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Sandton',
    interests: ['Beauty', 'Fashion'],
    followers: 32000,
    gender: 'team',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 1800,
    shortPitch: 'Team of beauty experts creating authentic product reviews and tutorials.',
    metricsBlurb: 'Avg 5.8% engagement',
    rating: 4.7,
    completedJobs: 156,
    avatarUrl: 'https://ui-avatars.com/api/?name=Beauty+Collective&size=128&background=ec4899&color=fff&bold=true',
  },
  {
    id: '4',
    name: 'David Nkomo',
    handle: '@durbanlocal',
    network: 'facebook',
    location: 'Umhlanga, Durban',
    city: 'Durban',
    suburb: 'Umhlanga',
    interests: ['Local Services', 'Automotive'],
    followers: 8500,
    gender: 'male',
    serviceTypes: ['review_booster', 'local_influencer'],
    startingFrom: 800,
    shortPitch: 'Local business advocate helping small businesses get authentic Google reviews.',
    metricsBlurb: 'Avg 4.5% engagement',
    rating: 4.6,
    completedJobs: 32,
    avatarUrl: 'https://ui-avatars.com/api/?name=David+Nkomo&size=128&background=0ea5e9&color=fff&bold=true',
  },
  {
    id: '5',
    name: 'Emma Thompson',
    handle: '@travelsouthafrica',
    network: 'multi',
    location: 'Camps Bay, Cape Town',
    city: 'Cape Town',
    suburb: 'Camps Bay',
    interests: ['Travel', 'Local Gems'],
    followers: 68000,
    gender: 'female',
    serviceTypes: ['ugc_creator', 'local_influencer', 'social_boost'],
    startingFrom: 3500,
    shortPitch: 'Travel content creator showcasing South African destinations and experiences.',
    metricsBlurb: 'Avg 7.3% engagement',
    rating: 4.9,
    completedJobs: 124,
    avatarUrl: 'https://ui-avatars.com/api/?name=Emma+Thompson&size=128&background=10b981&color=fff&bold=true',
  },
  {
    id: '6',
    name: 'Review Boost Pro',
    handle: '@reviewboostpro',
    network: 'multi',
    location: 'Pretoria, Gauteng',
    city: 'Pretoria',
    suburb: 'Pretoria',
    interests: ['Local Services'],
    followers: 12000,
    gender: 'team',
    serviceTypes: ['review_booster'],
    startingFrom: 950,
    shortPitch: 'Professional review generation service for local businesses across Gauteng.',
    metricsBlurb: 'Avg 3.8% engagement',
    rating: 4.5,
    completedJobs: 203,
    avatarUrl: 'https://ui-avatars.com/api/?name=Review+Boost+Pro&size=128&background=f59e0b&color=fff&bold=true',
  },
  {
    id: '7',
    name: 'Lisa van der Merwe',
    handle: '@lisavdm_beauty',
    network: 'tiktok',
    location: 'Rosebank, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Rosebank',
    interests: ['Beauty', 'Fashion'],
    followers: 28000,
    gender: 'female',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 1500,
    shortPitch: 'TikTok beauty creator with viral makeup and skincare content.',
    metricsBlurb: 'Avg 9.2% engagement',
    rating: 4.8,
    completedJobs: 67,
    avatarUrl: 'https://ui-avatars.com/api/?name=Lisa+van+der+Merwe&size=128&background=d946ef&color=fff&bold=true',
  },
  {
    id: '8',
    name: 'Cape Town Foodies',
    handle: '@capetownfoodies',
    network: 'instagram',
    location: 'Green Point, Cape Town',
    city: 'Cape Town',
    suburb: 'Green Point',
    interests: ['Food & Dining'],
    followers: 18500,
    gender: 'team',
    serviceTypes: ['review_booster', 'ugc_creator', 'local_influencer'],
    startingFrom: 1400,
    shortPitch: 'Group of food enthusiasts reviewing restaurants and cafes in Cape Town.',
    metricsBlurb: 'Avg 6.5% engagement',
    rating: 4.7,
    completedJobs: 91,
    avatarUrl: 'https://ui-avatars.com/api/?name=Cape+Town+Foodies&size=128&background=ef4444&color=fff&bold=true',
  },
  {
    id: '9',
    name: 'James Wilson',
    handle: '@jamesw_auto',
    network: 'youtube',
    location: 'Centurion, Pretoria',
    city: 'Pretoria',
    suburb: 'Centurion',
    interests: ['Automotive'],
    followers: 52000,
    gender: 'male',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 2800,
    shortPitch: 'Automotive YouTuber creating detailed car reviews and test drives.',
    metricsBlurb: 'Avg 5.1% engagement',
    rating: 4.8,
    completedJobs: 78,
    avatarUrl: 'https://ui-avatars.com/api/?name=James+Wilson&size=128&background=dc2626&color=fff&bold=true',
  },
  {
    id: '10',
    name: 'Wellness Warriors',
    handle: '@wellnesswarriorssa',
    network: 'multi',
    location: 'Bryanston, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Bryanston',
    interests: ['Fitness', 'Wellness'],
    followers: 24000,
    gender: 'team',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 1600,
    shortPitch: 'Wellness collective promoting healthy living and fitness products.',
    metricsBlurb: 'Avg 6.8% engagement',
    rating: 4.6,
    completedJobs: 54,
    avatarUrl: 'https://ui-avatars.com/api/?name=Wellness+Warriors&size=128&background=14b8a6&color=fff&bold=true',
  },
  {
    id: '11',
    name: 'Zara Patel',
    handle: '@zarapatel_travel',
    network: 'instagram',
    location: 'Ballito, Durban',
    city: 'Durban',
    suburb: 'Ballito',
    interests: ['Travel', 'Food & Dining'],
    followers: 35000,
    gender: 'female',
    serviceTypes: ['ugc_creator', 'local_influencer'],
    startingFrom: 2200,
    shortPitch: 'Travel and food content creator exploring KZN coast and local eateries.',
    metricsBlurb: 'Avg 7.5% engagement',
    rating: 4.9,
    completedJobs: 112,
    avatarUrl: 'https://ui-avatars.com/api/?name=Zara+Patel&size=128&background=8b5cf6&color=fff&bold=true',
  },
  {
    id: '12',
    name: 'Local Reviews SA',
    handle: '@localreviewssa',
    network: 'multi',
    location: 'Bloemfontein, Free State',
    city: 'Bloemfontein',
    suburb: 'Bloemfontein',
    interests: ['Local Services'],
    followers: 15000,
    gender: 'team',
    serviceTypes: ['review_booster'],
    startingFrom: 750,
    shortPitch: 'Dedicated review generation service for businesses in Free State region.',
    metricsBlurb: 'Avg 4.2% engagement',
    rating: 4.4,
    completedJobs: 187,
    avatarUrl: 'https://ui-avatars.com/api/?name=Local+Reviews+SA&size=128&background=6366f1&color=fff&bold=true',
  },
  {
    id: '13',
    name: 'Tumi Mokoena',
    handle: '@tumim_fashion',
    network: 'tiktok',
    location: 'Soweto, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Soweto',
    interests: ['Fashion', 'Beauty'],
    followers: 42000,
    gender: 'female',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 2000,
    shortPitch: 'Fashion influencer showcasing local brands and styling tips.',
    metricsBlurb: 'Avg 8.7% engagement',
    rating: 4.8,
    completedJobs: 95,
    avatarUrl: 'https://ui-avatars.com/api/?name=Tumi+Mokoena&size=128&background=a855f7&color=fff&bold=true',
  },
  {
    id: '14',
    name: 'Cape Winelands Explorer',
    handle: '@capewinelandsexplorer',
    network: 'instagram',
    location: 'Stellenbosch, Cape Town',
    city: 'Cape Town',
    suburb: 'Stellenbosch',
    interests: ['Food & Dining', 'Travel', 'Local Gems'],
    followers: 29000,
    gender: 'unspecified',
    serviceTypes: ['ugc_creator', 'local_influencer'],
    startingFrom: 1900,
    shortPitch: 'Exploring winelands, restaurants, and hidden gems in the Western Cape.',
    metricsBlurb: 'Avg 6.9% engagement',
    rating: 4.7,
    completedJobs: 73,
    avatarUrl: 'https://ui-avatars.com/api/?name=Cape+Winelands+Explorer&size=128&background=06b6d4&color=fff&bold=true',
  },
  {
    id: '15',
    name: 'Social Boost Agency',
    handle: '@socialboostagency',
    network: 'multi',
    location: 'Sandton, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Sandton',
    interests: ['Local Services'],
    followers: 25000,
    gender: 'team',
    serviceTypes: ['social_boost'],
    startingFrom: 1100,
    shortPitch: 'Full-service social media boost and shoutout service across all platforms.',
    metricsBlurb: 'Avg 5.3% engagement',
    rating: 4.6,
    completedJobs: 245,
    avatarUrl: 'https://ui-avatars.com/api/?name=Social+Boost+Agency&size=128&background=3b82f6&color=fff&bold=true',
  },
  {
    id: '16',
    name: 'Nomsa Dlamini',
    handle: '@nomsad_beauty',
    network: 'instagram',
    location: 'Maboneng, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Maboneng',
    interests: ['Beauty'],
    followers: 16500,
    gender: 'female',
    serviceTypes: ['ugc_creator', 'review_booster'],
    startingFrom: 1300,
    shortPitch: 'Beauty content creator specializing in skincare and makeup reviews.',
    metricsBlurb: 'Avg 7.1% engagement',
    rating: 4.8,
    completedJobs: 58,
    avatarUrl: 'https://ui-avatars.com/api/?name=Nomsa+Dlamini&size=128&background=f43f5e&color=fff&bold=true',
  },
  {
    id: '17',
    name: 'Durban Food Scene',
    handle: '@durbanfoodscene',
    network: 'facebook',
    location: 'Morningside, Durban',
    city: 'Durban',
    suburb: 'Morningside',
    interests: ['Food & Dining', 'Local Gems'],
    followers: 22000,
    gender: 'team',
    serviceTypes: ['review_booster', 'local_influencer'],
    startingFrom: 1000,
    shortPitch: 'Community-driven food reviews and recommendations in Durban area.',
    metricsBlurb: 'Avg 5.6% engagement',
    rating: 4.5,
    completedJobs: 134,
    avatarUrl: 'https://ui-avatars.com/api/?name=Durban+Food+Scene&size=128&background=ea580c&color=fff&bold=true',
  },
  {
    id: '18',
    name: 'Fitness Freak SA',
    handle: '@fitnessfreaksa',
    network: 'youtube',
    location: 'Fourways, Johannesburg',
    city: 'Johannesburg',
    suburb: 'Fourways',
    interests: ['Fitness'],
    followers: 38000,
    gender: 'male',
    serviceTypes: ['ugc_creator', 'social_boost'],
    startingFrom: 2400,
    shortPitch: 'Fitness YouTuber creating workout content and supplement reviews.',
    metricsBlurb: 'Avg 6.4% engagement',
    rating: 4.7,
    completedJobs: 82,
    avatarUrl: 'https://ui-avatars.com/api/?name=Fitness+Freak+SA&size=128&background=16a34a&color=fff&bold=true',
  },
];

// Service type labels
export const SERVICE_TYPE_LABELS: Record<ServiceType, string> = {
  review_booster: 'Review Boosters',
  ugc_creator: 'UGC Creators',
  local_influencer: 'Local Influencers',
  social_boost: 'Social Boost (Posts & Shoutouts)',
};

// Available interests
export const AVAILABLE_INTERESTS = [
  'Food & Dining',
  'Beauty',
  'Fitness',
  'Travel',
  'Automotive',
  'Local Services',
  'Fashion',
  'Wellness',
  'Local Gems',
];

// Follower ranges
export type FollowerRange = 'any' | '0-10k' | '10k-50k' | '50k-250k' | '250k+';

export interface FollowerRangeOption {
  value: FollowerRange;
  label: string;
  min?: number;
  max?: number;
}

export const FOLLOWER_RANGES: FollowerRangeOption[] = [
  { value: 'any', label: 'Any' },
  { value: '0-10k', label: '0–10K', min: 0, max: 10000 },
  { value: '10k-50k', label: '10K–50K', min: 10000, max: 50000 },
  { value: '50k-250k', label: '50K–250K', min: 50000, max: 250000 },
  { value: '250k+', label: '250K+', min: 250000 },
];

// Gender options
export type GenderFilter = 'any' | Gender;

export const GENDER_OPTIONS: { value: GenderFilter; label: string }[] = [
  { value: 'any', label: 'Any' },
  { value: 'female', label: 'Female' },
  { value: 'male', label: 'Male' },
  { value: 'team', label: 'Mixed / Team' },
  { value: 'unspecified', label: 'Not specified' },
];

